included:
  - RomKit
  - RomKitCLI
  - RomKitTests
  
excluded:
  - .build
  - Package.swift
  - Tests/LinuxMain.swift

disabled_rules:
  - todo  # Allow TODO and FIXME comments
  
opt_in_rules:
  - force_unwrapping
  - empty_count
  - closure_spacing
  
line_length:
  warning: 200
  error: 300
  ignores_comments: true
  
type_body_length:
  warning: 350
  error: 500
  
file_length:
  warning: 500
  error: 1000
  
function_body_length:
  warning: 50
  error: 100
  
identifier_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - db
    - to
    - at
    - ok