name: mac-p7zip-release

on:
  release:
    tags:
      - '*'

jobs:
  build:
    name: macos-Release
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: build 7zz & check
      run: |
        mkdir mac-p7zip
        mkdir mac-p7zip/bin
        mkdir mac-p7zip/lib
        export PROJECT_ROOT=`pwd`
        cd CPP/7zip/Bundles/Alone2
        make -f makefile.gcc
        INSTALL_PREFIX=$PROJECT_ROOT/mac-p7zip make -f makefile.gcc install
        git clone  https://github.com/jinfeihan57/p7zip_test_utils.git
        cd p7zip_test_utils/check
        bash check.sh $PROJECT_ROOT/mac-p7zip/bin/7zz
    - name: build 7z.so
      run: |
        cd CPP/7zip/Bundles/Format7zF
        make -f makefile.gcc
        INSTALL_PREFIX=$PROJECT_ROOT/mac-p7zip make -f makefile.gcc install
    - name: p7zip
      run: |
        ./mac-p7zip/bin/7zz a mac-p7zip.7z mac-p7zip -y
        ./mac-p7zip/bin/7zz a mac-p7zip.zip mac-p7zip -y
    - name: Upload p7zip binary
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: mac-p7zip.*
        asset_name: mac-p7zip
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
        body: "This is mac binary release using make"
